server:
  port: 8040
  
spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
feign:
  hystrix:
    enabled: true
hystrix:
  metrics:
    enabled: true
management:
  endpoint:
    hystrix:
      stream:
        enabled: true
eureka:
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1